In [25]:
# linear regression multiple varibles...

In [46]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn import linear_model


In [27]:

df=pd.read_csv("homepri.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [28]:
#3000 sqr fr area ,3 bedroom 40yrs
#2500 sq fit area,4bedrom ,5 yrs
          #price = m1*area+m2*bedroom +m3*age+b      (b=incetpect)

In [48]:
#data cleaning
import math

median_bed=math.floor(df.bedrooms.median())
median_bed

3

In [50]:
df.bedrooms=df.bedrooms.fillna(median_bed)        #filling the median in place of null
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [54]:
reg= linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)          

LinearRegression()

In [56]:
reg.coef_


array([   137.25, -26025.  ,  -6825.  ])

In [58]:
reg.intercept_

383724.9999999998

In [102]:
reg.predict([[3000,3,40]])

C:\Users\ranaa\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [62]:
137.25*3000+-26025*3+-6825*40+383724.9999999998

444399.9999999998

In [64]:
reg.predict([[2500,4,5]])

C:\Users\ranaa\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [66]:
137.25*2500+-26025*4+-6825*5+383724.9999999998          #for (2500,4,5)

588624.9999999998

In [68]:
reg.predict([[5000,3,10]])

C:\Users\ranaa\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([923650.])

In [70]:
# part 2   pickle - serialize the object into- python file
import pickle 

In [72]:
model=linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [74]:
model.coef_


array([134.07534247])

In [76]:
model.intercept_

176232.87671232875

In [78]:
model.predict([[5000]])

C:\Users\ranaa\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([846609.5890411])

In [82]:
# with open ('model
with open('model_pickle','wb')as file:
   pickle.dump(model,file)

In [84]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [86]:
mp.coef_

array([134.07534247])

In [88]:
mp.intercept_

176232.87671232875

In [109]:
model.predict([[1300]])

C:\Users\ranaa\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([350530.82191781])